version: '2'
services:
 db:
   image: postgres
   restart: always
   volumes:
     - /home/$USER/Virtualiza-o_Redes_TPs/tp1/postgres_data:/var/lib/postgresql/data
   networks:
     - network_1
 auth_service:
   image: php:7.0-apache
   restart: always
   ports:
     - '8888:80'
   volumes:
     - /home/$USER/Virtualiza-o_Redes_TPs/tp1/authentication_service:/var/www/html
   networks:
     - network_1
     - network_2
 mail_service:
   image: php:7.0-apache
   restart: always
   ports:
     - '8889:80'
   volumes:
     - /home/$USER/Virtualiza-o_Redes_TPs/tp1/mail_service:/var/www/html  
   networks:
     - network_2
     - network_3
 mail:
   image: namshi/smtp
   restart: always
   networks:
     - network_3
networks:
    network_1:
      driver: bridge
    network_2:
      driver: bridge
    network_3:
      driver: bridge
