version: '2'
services:
 db:
   image: postgres
   container_name: postgres
   restart: always
   volumes:
     - ./postgres_data:/var/lib/postgresql/data
     - ./scripts_postgres:/docker-entrypoint-initdb.d
   networks:
     - network_1
 auth:
   build: ./authentication_service
   container_name: auth
   restart: always
   ports:
     - '8888:80'
   volumes:
     - ./authentication_service:/var/www/html
   networks:
     - network_1
     - network_2
 mail:
   image: php:7.0-apache
   container_name: mail
   restart: always
   ports:
     - '8889:80'
   volumes:
     - ./mail_service:/var/www/html
   networks:
     - network_2
     - network_3
 mailServer:
   image: namshi/smtp
   container_name: mailServer
   restart: always
   networks:
     - network_3
 haproxy:
   image: haproxy:1.7
   container_name: haproxy
   ports:
     - '9000:80'
   volumes:
     - ./haproxy:/usr/local/etc/haproxy/
   networks:
     - network_2

networks:
    network_1:
      driver: bridge
    network_2:
      driver: bridge
    network_3:
      driver: bridge
