version: '2'
services:
  mininet:
    image: carlosilva96/virtualiza-o_redes_tps
    container_name: mininet
    restart: always
    privileged: true
    tty: true
    environment:
      - DISPLAY
    volumes: 
      - /lib/modules:/lib/modules
      - ${PWD}/map:/home/ubuntu
      - /tmp/.X11-unix:/tmp/.X11-unix
