version: '2'
services:
  mininet:
    image: carlosilva96/virtualiza-o_redes_tps
    container_name: mininet
    restart: always
    privileged: true
    volumes: 
      - /lib/modules:/lib/modules
      - ${PWD}/map:/home/ubuntu
